version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/M3_App
hooks:
  BeforeInstall:
    - location: scripts/start_server.sh
      runas: root
  AfterInstall:
    - location: scripts/on_server.sh
      runas: root
